---
id: "docker_registry"
vm_id: 120
template_id: "1000"
hostname: "registry"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 1
cpu_sockets: 1
memory: 512
vm_user: "sysadmin"
disks:
  disk0:
    interface: "virtio0"
    storage: "local-lvm"
    size: 70
    iothread: true
    discard: "ignore"
vm_tags: ["registry", "docker", "terraform"]
template_tag: "registry"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
network_devices:
  eth0:
    bridge: "vnet01"
    addresses: "10.0.0.250/24"
    gateway4: "10.0.0.1"
    routes:
      - to: "default"
        via: "10.0.0.1"
        metric: "10"            
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files: []
cmds: [
  "usermod -aG docker user"
]
deploy: true
