---
id: "nfs_server_alpine"
vm_id: 115
template_id: "1000"
hostname: "nfs-server-apline"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 1
cpu_sockets: 1
memory: 512
vm_user: "sysadmin"
disks: {}
vm_tags: ["nfs", "alpine", "terraform"]
template_tag: "router"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
network_devices:
  eth0:
    bridge: "vmbr0"
    addresses: "192.168.1.58/24"
    gateway4: "192.168.1.1"
    routes:
      - to: "default"
        via: "192.168.1.1"
        metric: "10"         
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files: []
cmds: [
  "sleep 3",
  "apk --no-cache --cache-max-age 30 add wget",
  "wget http://192.168.1.29:8080/files/nfs/nfs-server-setup-alpine.sh",
  "bash $PWD/nfs-server-setup-alpine.sh", 
  # "rm $PWD/nfs-server-setup-alpine.sh"
]
deploy: false
