---
id: "nginxproxymanager"
vm_id: 110
template_id: "1000"
hostname: "nginxproxymanager"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 2
cpu_sockets: 1
memory: 1024
vm_user: "sysadmin"
disks:
  disk0:
    interface: "virtio0"
    storage: "local-lvm"
    size: 14
    iothread: true
    discard: "ignore"
bridges: [
  "vmbr0"
]
vm_tags: ["router", "current", "terraform"]
template_tag: "router"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
network_devices:
  eth0:
    bridge: "vmbr0"
    addresses: "192.168.1.114/24"
    gateway4: "192.168.1.1"
    routes: []
  eth1:
    bridge: "vnet01"
    addresses: "10.0.0.100/24"
    gateway4: "10.0.0.1"
    # routes:
    #   - to: "10.0.0.0/24"
    #     via: "10.0.0.1"
    #     metric: "1"       
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files: []
# files:
#    - path: "/opt/iptables.rules"
#      permissions: "0755"
#      content: |
#        # Generated by iptables-save v1.8.10 (nf_tables) on Mon Dec  8 15:56:30 2025
#        *filter
#        :INPUT ACCEPT [9920:2637840]
#        :FORWARD DROP [0:0]
#        :OUTPUT ACCEPT [9965:916160]

cmds: [
  "usermod -aG docker user",
  "su - user -c \"mkdir /home/user/nginx\"",
  "su - user -c \"cd /home/user/nginx; wget http://${http_server_url}/files/nginxproxymanager/configs/docker-compose.yml\"",
  "su - user -c \"cd /home/user/nginx; wget http://${http_server_url}/files/nginxproxymanager/data/data.tgz\"",      
  "su - user -c \"cd /home/user/nginx; wget http://${http_server_url}/files/nginxproxymanager/data/letsencrypt.tgz\"",
  "su - user -c \"cd /home/user/nginx; tar xvzf data.tgz && tar xvzf letsencrypt.tgz && rm data.tgz letsencrypt.tgz\"",
  "su - user -c \"cd /home/user/nginx; docker-compose up -d\""
]
deploy: true
