---
id: "runner_nixos"
vm_id: 9999
replicas: 1
hostname: "runner-nixos"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 4
cpu_sockets: 1
bios: "ovmf"
efi_disk:
  datastore_id: "local-lvm"
  file_format: "raw"
  type: "4m"
  pre_enrolled_keys: false  
# boot_order:
#   - "ide3"
#   - "virtio0"
#   - "net0"
  
agent: false
cdrom:
  file_id: "local:iso/nixos-25.11pre-git-x86_64-linux.iso"
memory: 4096
vm_user: "sysadmin"
vm_tags: ["live", "nixos", "terraform"]
started: true
onboot: false
target_node: "pve"
target_node_domain: ""
firewall_enabled: false
# fw_rules:
#   - type: "in"
#     action: "ACCEPT"
#     macro: "SSH"
#     comment: "SSH local"
#     log: "nolog"
#     interface: "net0"
#     enabled: true
#   - type: "out"
#     action: "ACCEPT"
#     log: "nolog"
#     enabled: true    
dns_servers: ["8.8.8.8", "8.8.4.4"]
network_devices:
  ens18:
    # bridge: "vnet01"
    # firewall: false
    bridge: "vnet01"
    addresses: "10.0.0.138/24"
    gateway4: "10.0.0.1"
    firewall: true
    dhcp: false    
disks:    
  disk0:
    interface: "virtio0"
    storage: "local-lvm"
    size: 25
    iothread: true
    discard: "ignore"                
users: []
files: []
cmds: []
enable_cloud_init: true
deploy: true