---
id: "testmachinealpine"
vm_id: 700
replicas: 2
template_id: "1000"
hostname: "testmachinealpine"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 4
cpu_sockets: 1
memory: 4096
vm_user: "sysadmin"
disks:
 disk0:
    interface: "virtio0"
    storage: "local-lvm"
    size: 45
    iothread: true
    discard: "ignore"
# bios: "ovmf"
# efi_disk:
#   datastore_id: "local-lvm"
#   file_format: "raw"
#   type: "4m"
#   pre_enrolled_keys: false      
vm_tags: ["test", "alpine", "terraform", "replicas"]
template_tag: "router"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
firewall_enabled: false
secgroups:
  - security_group: "test700"
    comment: "From security group"
    iface: "net0"
# fw_rules:
#   - type: "in"
#     action: "ACCEPT"
#     comment: "Allow HTTP"
#     dest: "192.168.1.5"
#     dport: "80"
#     proto: "tcp"
#     log: "info"
#     enabled: false

network_devices:
  # eth0:
  #   bridge: "vmbr0"
  #   addresses: "192.168.1.90/24"
  #   gateway4: "192.168.1.1"
  #   firewall: true
  #   dhcp: false
  eth0:
    bridge: "vnet01"
    addresses: "10.0.0.90/24"
    gateway4: "10.0.0.1"
    firewall: false
    dhcp: false
    # routes:
    #   - to: "default"
    #     via: "10.0.0.1"
    #     metric: "10"            
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKptwbs9lkk56DbyH8WXpSESgqiRDPHRjgI/grUPi4Vm user@nixos"
    #ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files:
  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    permissions: '0644'
    owner: root:root
  - path: /home/user/cmd
    content: |
      #!/bin/sh
      #ssh user@10.10.0.12 "docker run -t -v nix-store:/nix 10.0.0.250:5000/nixos-anywhere bash -ic \"colmena --help\""
      #ssh user@10.10.0.12 "docker run -t -v nix-store:/nix 10.0.0.250:5000/nixos-anywhere bash -ic \"nix-shell -p iputils --run 'ping -c2 10.0.0.90'\""
      ssh user@10.10.0.12 "docker run -e SSHPASS=toor -t -v nix-store:/nix 10.0.0.250:5000/nixos-anywhere bash -ic \"nix-shell -p nixos-anywhere --run 'nixos-anywhere --flake .#serveur --build-on local --env-password --option require-sigs false --debug user@10.0.0.90'\""
    permissions: '0755'


cmds: [
  "usermod -aG docker user",
  # "echo \"PerSourcePenalties no\" >> /etc/ssh/sshd_config",
  # "rc-service sshd restart",
  # "chown -R user:user /home/user"
]
cloudinit_templates:
  user_data_path: "cloud-init/user_data_hostname"
deploy: false
