---
id: "testmachinealpine2"
vm_id: 800
replicas: 0
template_id: "1000"
hostname: "testmachinealpine2"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 1
cpu_sockets: 1
memory: 512
vm_user: "sysadmin"
disks: {}
vm_tags: ["test", "alpine", "terraform", "replicas"]
template_tag: "router"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
firewall_enabled: false
secgroups:
  - security_group: "test700"
    comment: "From security group"
    iface: "net0"
# fw_rules:
#   - type: "in"
#     action: "ACCEPT"
#     comment: "Allow HTTP"
#     dest: "192.168.1.5"
#     dport: "80"
#     proto: "tcp"
#     log: "info"
#     enabled: false

network_devices:
  eth0:
    bridge: "vmbr0"
    addresses: "192.168.1.197/24"
    gateway4: "192.168.1.1"
    firewall: true
    routes:
      - to: "10.0.0.0/24"
        via: "192.168.1.100"
        metric: "1"
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files:
  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    permissions: '0644'
    owner: root:root
cmds: [
  "usermod -aG docker user",
  "apk add curl"
]
deploy: true