---
id: "testnfs"
vm_id: 940
target_node: "pve"
description: "Container managed by terraform: python testing for yfinance"
tags: ["test", "terraform"]
hostname: "testnfs"
cpu:
  cores: 2
memory:
  dedicated: 512
network_interfaces:
  eth0:
    name: "eth0"
    bridge: "vmbr0"
ipv4_configs:
  eth0:
    address: "192.168.1.244/24"
    gateway: "192.168.1.1"

disks:
  disk0:
    datastore_id: "rpi"
    size: 10

startup:
  order: "99"
  up_delay: "240"

unprivileged: true

hook_script_file_id: ""
deploy: false
