---
id: "test"
vm_id: 940
replicas: 1
target_node: "pve"
description: "Container managed by terraform"
tags: ["test", "terraform"]
hostname: "test"
cpu:
  cores: 2
memory:
  dedicated: 512
network_interfaces:
  eth0:
    name: "eth0"
    bridge: "vnet01"
ipv4_configs:
  eth0:
    address: "10.0.0.244/24"
    gateway: "10.0.0.1"

disks:
  disk0:
    #datastore_id: "rpi"
    datastore_id: "local-lvm"
    size: 10

startup:
  order: "99"
  up_delay: "240"

unprivileged: true

hook_script_file_id: ""
enable_provision: true
deploy: false