---
id: "testvm"
vm_id: 1300
replicas: 1
template_id: "1000"
hostname: "testvm"
domain: "net.local"
cpu_type: "x86-64-v2-AES"
cpu_cores: 1
cpu_sockets: 1
memory: 1024
vm_user: "sysadmin"
disks:
 disk0:
    interface: "virtio0"
    storage: "local-lvm"
    size: 45
    iothread: true
    discard: "ignore"   
vm_tags: ["test", "alpine", "terraform", "replicas"]
template_tag: "router"
started: true
onboot: true
target_node: "pve"
target_node_domain: ""
dns_servers: ["8.8.8.8", "8.8.4.4"]
firewall_enabled: false
secgroups: []

network_devices:
  eth0:
    bridge: "vnet01"
    addresses: "10.0.0.96/24"
    gateway4: "10.0.0.1"
    firewall: false
    dhcp: false          
users:
  - name: "user"
    password: "$6$tGz.h5alKsD5IOP2$yfQ1RTnXjdLnmCQxFG70Jf3d24YAb8Bsb/qZ/iW0aokkahPQ8qlRhgC2ZpVYkcK.CQh579k3IF3f2LTDAMsKH/"
    groups: "[adm, sudo]"
    lock_passwd: "false"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKptwbs9lkk56DbyH8WXpSESgqiRDPHRjgI/grUPi4Vm user@nixos"
    #ssh_authorized_keys: "\n      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1oFq0GYt8j7vg2nNAJNzwBtqrdOUDp8CMQwLRiz4Vz user@ull"

files:
  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    permissions: '0644'
    owner: root:root

cmds: [
  "echo ${http_server_url} > /home/user/proof"
]
cloudinit_templates:
  user_data_path: "cloud-init/user_data_hostname"
deploy: true
