image:
  name: hashicorp/packer:latest

before_script:
  - packer --version

stages:
  - validate

validate:
  stage: validate
  script:
    - packer validate .

#build:
#  stage: build
#  environment: production
#  script:
#    - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: manual

